# Generated by Django 5.1.6 on 2026-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0059_customuser_referral_code_customuser_referral_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_earnings',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_coupon_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
