# Generated by Django 5.1.6 on 2026-03-10 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0061_final_referral_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_coupon_generated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 10, 8, 0, 37, 136196, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReferralCoupon',
        ),
    ]
