"""
Django settings for sanjeri_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--^v2*dd7n=%tr0g%=s46wfv4!t3sl%u)p=9j4cq(wf!zr7h%3&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ancyfaisal.pythonanywhere.com', '127.0.0.1']
# ALLOWED_HOSTS = ['https://ancyfaisal.github.io/sanjeri_ecomerce/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'sanjeri_app',
    'newapp',
]

# SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

ROOT_URLCONF = 'sanjeri_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sanjeri_app.context_processors.cart_and_wishlist_context',
                # 'sanjeri_app.context_processors.wishlist_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanjeri_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sanjeri_db',
        'USER': 'sanjeri_user',
        'PASSWORD': 'mypassword',   
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'sanjeri_app.CustomUser'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "ancyfaisal54@gmail.com"
EMAIL_HOST_PASSWORD = "sxbk zcwq rjel hcki"

# Authentication backends
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',   # default
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
    # 'sanjeri_app.backends.CustomUserBackend',
)

# Allauth settings for seamless social login
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGOUT_ON_GET = True  # Skip logout confirmation

# Social account settings to skip intermediate pages
SOCIALACCOUNT_LOGIN_ON_GET = True  # THIS IS THE KEY SETTING
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = True

# Custom adapter (if you're using it)
SOCIALACCOUNT_ADAPTER = 'sanjeri_app.adapters.CustomSocialAccountAdapter'

# Login/Logout URLs
LOGIN_REDIRECT_URL = 'homepage'
LOGOUT_REDIRECT_URL = 'user_login'
LOGIN_URL = '/user_login/'

# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': '77221304374-rpe32gue5hchc7tl1bda2ajh0j9bied6.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}

# Payment Gateway Settings
RAZORPAY_KEY_ID = 'rzp_test_YOUR_KEY_ID'  # Get from Razorpay dashboard
RAZORPAY_KEY_SECRET = 'YOUR_RAZORPAY_SECRET'  # Get from Razorpay dashboard

# PayPal Settings
PAYPAL_CLIENT_ID = 'YOUR_PAYPAL_CLIENT_ID'
PAYPAL_CLIENT_SECRET = 'YOUR_PAYPAL_SECRET'
PAYPAL_MODE = 'sandbox'  # 'sandbox' or 'live'

# ==================== RAZORPAY TEST ====================
# TEMPORARY - Replace with your actual keys
RAZORPAY_KEY_ID = 'rzp_test_1DP5mmOlF5G5ag'  # Example format
RAZORPAY_KEY_SECRET = 'wFYmNv4Wt5ZbM7fE8qH3rK6pL9'  # Example format

print("=" * 50)
print("RAZORPAY CONFIG CHECK:")
print(f"Key ID: {RAZORPAY_KEY_ID}")
print(f"Key ID Length: {len(RAZORPAY_KEY_ID)}")
print(f"Key Secret Length: {len(RAZORPAY_KEY_SECRET)}")
print("=" * 50)